#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""AmazingData 各表的字段说明 —— **生成物，不要手改**。

    重新生成：tools/parse_manual_fields.py（怎么跑、判据是什么都在它的 docstring 里）

来源两处：字段名与列序取自 wheel 里 `download_xxx()` 的 `columns_list` 常量元组
（那就是返回值真实的列），中文说明取自手册 PDF 的字段表。
🔴 不要照 PDF 抄字段名 —— pypdf 抽出来的名字被排版拆了字
（`STA TEMENT_TYPE` / `ACC_RECEIV ABLE`），对不上真实返回值**而不报错**。

结构：FIELDS[表名] = {字段名: (类型, 说明)}；`__source__` 键是那张表说明的出处。
"""

# 由 tools/parse_manual_fields.py 生成，共 34 张表 / 783 个字段
FIELDS = {
    'stock_basic': {
        '__source__': '手册「stock_basic的字段说明」；列名与列序取自 wheel 的 columns_list（10 列）',
        'MARKET_CODE': ('string', '证券代码'),
        'SECURITY_NAME': ('string', '证券简称'),
        'COMP_NAME': ('string', '证券中文名称'),
        'PINYIN': ('string', '中文拼音简称'),
        'COMP_NAME_ENG': ('string', '证券英文名称'),
        'LISTDATE': ('int', '上市日期'),
        'DELISTDATE': ('int', '退市日期'),
        'LISTPLATE_NAME': ('string', '上市板块名称'),
        'COMP_SNAME_ENG': ('string', '英文名称缩写'),
        'IS_LISTED': ('int', '上市状态 1：上市交易3：终止上市'),
    },
    'history_stock_status': {
        '__source__': '手册「history_stock_status的字段说明」；列名与列序取自 wheel 的 columns_list（11 列）',
        'MARKET_CODE': ('string', '证券代码'),
        'TRADE_DATE': ('string', '日期'),
        'PRECLOSE': ('float', '前收价'),
        'HIGH_LIMITED': ('float', '涨停价'),
        'LOW_LIMITED': ('float', '跌停价'),
        'PRICE_HIGH_LMT_RATE': ('float', '涨停价上限'),
        'PRICE_LOW_LMT_RATE': ('float', '跌停价下限'),
        'IS_ST_SEC': ('string', '是否 ST 1表示是，0 表示否'),
        'IS_SUSP_SEC': ('string', '是否停牌 1表示是，0 表示否'),
        'IS_WD_SEC': ('string', '是否除息 1表示是，0 表示否'),
        'IS_XR_SEC': ('string', '是否除权 1表示是，0 表示否'),
    },
    'bj_code_mapping': {
        '__source__': '手册「bj_code_mapping的字段说明」',
        'OLD_CODE': ('string', '旧代码'),
        'NEW_CODE': ('string', '新代码'),
        'SECURITY_NAME': ('string', '证券简称'),
    },
    'balance_sheet': {
        '__source__': '手册「balance_sheet的字段说明」；列名与列序取自 wheel 的 columns_list（179 列）',
        'MARKET_CODE': ('str', '证券代码'),
        'SECURITY_NAME': ('str', '证券简称'),
        'STATEMENT_TYPE': ('str', '报表类型 参看报表类型代码表'),
        'REPORT_TYPE': ('str', '报告期名称 参看报告期名称'),
        'REPORTING_PERIOD': ('str', '报告期'),
        'ANN_DATE': ('str', '公告日期'),
        'ACTUAL_ANN_DATE': ('str', '实际公告日期'),
        'ACC_PAYABLE': ('float', '应付票据及应付账款'),
        'ACC_RECEIVABLE': ('float', '应收票据及应收账款'),
        'ACC_RECEIVABLES': ('float', '应收款项'),
        'ACCRUED_EXP': ('float', '预提费用'),
        'ACCT_PAYABLE': ('float', '应付账款'),
        'ACCT_RECEIVABLE': ('float', '应收账款'),
        'ACT_TRADING_SEC': ('float', '代理买卖证券款'),
        'ACT_UW_SEC': ('float', '代理承销证券款'),
        'ADV_PREM': ('float', '预收保费'),
        'ADV_RECEIPT': ('float', '预收款项'),
        'AGENCY_ASSETS': ('float', '代理业务资产'),
        'AGENCY_BUSINESS_LIAB': ('float', '代理业务负债'),
        'ANTICIPATION_LIAB': ('float', '预计负债'),
        'ASSET_DEP_FUNDS_OTH_FIN_INST': ('float', '存放同业和其它金融机构款项'),
        'BONDS_PAYABLE': ('float', '应付债券'),
        'CAP_RESV': ('float', '资本公积金'),
        'CAP_STOCK': ('float', '股本 金额（元），公布值'),
        'CASH_CENTRAL_BANK_DEPOSITS': ('float', '现金及存放中央银行款项'),
        'CED_INSUR_CONT_RESERVES_RCV': ('float', '应收分保合同准备金'),
        'CLAIMS_PAYABLE': ('float', '应付赔付款'),
        'CLIENTS_FUND_DEPOSIT': ('float', '客户资金存款'),
        'CLIENTS_RESERVES': ('float', '客户备付金'),
        'CNVD_DIFF_FOREIGN_CURR_STAT': ('float', '外币报表折算差额'),
        'COMP_TYPE_CODE': ('int', '公司类型代码 1：非金融类 2：银行 3：保险 4：证券'),
        'CONST_IN_PROC': ('float', '在建工程'),
        'CONST_IN_PROC_TOTAL': ('float', '在建工程(合计)(元)'),
        'CONSUMP_BIO_ASSETS': ('float', '消耗性生物资产'),
        'CONT_ASSETS': ('float', '合同资产 单位（元）'),
        'CONT_LIABILITIES': ('float', '合同负债 单位（元）'),
        'CURRENCY_CAP': ('float', '货币资金'),
        'CURRENCY_CODE': ('float', '货币代码'),
        'DEBT_INV': ('float', '债权投资(元)'),
        'DEFERRED_INC_NONCUR_LIAB': ('float', '递延收益-非流动负债'),
        'DEFERRED_INCOME': ('float', '递延收益'),
        'DEFERRED_TAX_ASSETS': ('float', '递延所得税资产'),
        'DEFERRED_TAX_LIAB': ('float', '递延所得税负债'),
        'DEP_RECEIVED_IB_DEP': ('float', '吸收存款及同业存放'),
        'DEPOSIT_CAP_RECOG': ('float', '存出资本保证金'),
        'DEPOSIT_TAKING': ('float', '吸收存款'),
        'DEPOSITS_RECEIVED': ('float', '存入保证金'),
        'DER_FIN_ASSETS': ('float', '衍生金融资产'),
        'DERI_FIN_LIAB': ('float', '衍生金融负债'),
        'DEVELOP_EXP': ('float', '开发支出'),
        'DISPOSAL_FIX_ASSETS': ('float', '固定资产清理'),
        'DIV_PAYABLE': ('float', '应付股利'),
        'DIV_RECEIVABLE': ('float', '应收股利'),
        'EMPL_PAY_PAYABLE': ('float', '应付职工薪酬'),
        'ENGIN_MAT': ('float', '工程物资'),
        'FIN_ASSETS_AVA_FOR_SALE': ('float', '可供出售金融资产'),
        'FIN_ASSETS_COST_SHARING': ('float', '以摊余成本计量的金融资产'),
        'FIN_ASSETS_FAIR_VALUE': ('float', '以公允价值计量且其变动计入其他综合收益的金融资产'),
        'FIXED_ASSETS': ('float', '固定资产'),
        'FIXED_ASSETS_TOTAL': ('float', '固定资产(合计)(元)'),
        'FIXED_TERM_DEPOSITS': ('float', '定期存款'),
        'GOODWILL': ('float', '商誉'),
        'GUA_DEPOSITS_PAID': ('float', '存出保证金'),
        'GUA_PLEDGE_LOANS': ('float', '保户质押贷款'),
        'HOLD_ASSETS_FOR_SALE': ('float', '持有待售的资产'),
        'HOLD_TO_MTY_INV': ('float', '持有至到期投资'),
        'INC_PLEDGE_LOAN': ('float', '其中:质押借款'),
        'INCL_TRADING_SEAT_FEES': ('float', '其中:交易席位费'),
        'IND_ACCT_ASSETS': ('float', '独立账户资产'),
        'IND_ACCT_LIAB': ('float', '独立账户负债'),
        'INSURED_DEPOSIT_INV': ('float', '保户储金及投资款'),
        'INSURED_DIV_PAYABLE': ('float', '应付保单红利'),
        'INT_RECEIVABLE': ('float', '应收利息'),
        'INTANGIBLE_ASSETS': ('float', '无形资产'),
        'INTEREST_PAYABLE': ('float', '应付利息'),
        'INV': ('float', '存货'),
        'INV_REALESTATE': ('float', '投资性房地产'),
        'LEASE_LIABILITY': ('float', '租赁负债'),
        'LEND_FUNDS': ('float', '融出资金'),
        'LENDING_FUNDS': ('float', '拆出资金'),
        'LESS_TREASURY_STK': ('float', '减:库存股'),
        'LIA_HFS': ('float', '持有待售的负债'),
        'LIAB_DEP_FUNDS_OTH_FIN_INST': ('float', '同业和其它金融机构存放款项'),
        'LIFE_INSUR_RESV': ('float', '寿险责任准备金'),
        'LOAN_CENTRAL_BANK': ('float', '向中央银行借款'),
        'LOANS_AND_ADVANCES': ('float', '发放贷款及垫款'),
        'LOANS_FROM_OTH_BANKS': ('float', '拆入资金'),
        'LT_DEFERRED_EXP': ('float', '长期待摊费用'),
        'LT_EMP_COMP_PAY': ('float', '长期应付职工薪酬'),
        'LT_EQUITY_INV': ('float', '长期股权投资'),
        'LT_HEALTH_INSUR_RESV': ('float', '长期健康险责任准备金'),
        'LT_LOAN': ('float', '长期借款'),
        'LT_PAYABLE': ('float', '长期应付款'),
        'LT_PAYABLE_TOTAL': ('float', '长期应付款(合计)(元)'),
        'LT_RECEIVABLES': ('float', '长期应收款'),
        'MINORITY_EQUITY': ('float', '少数股东权益'),
        'NOM_RISKS_PREP': ('float', '一般风险准备'),
        'NONCUR_ASSETS_DUE_WITHIN_1Y': ('float', '一年内到期的非流动资产'),
        'NONCUR_LIAB_DUE_WITHIN_1Y': ('float', '一年内到期的非流动负债'),
        'NOTES_PAYABLE': ('float', '应付票据'),
        'NOTES_RECEIVABLE': ('float', '应收票据'),
        'OIL_AND_GAS_ASSETS': ('float', '油气资产'),
        'OTH_COMP_INCOME': ('float', '其他综合收益'),
        'OTH_EQUITY_TOOLS': ('float', '其他权益工具'),
        'OTH_EQUITY_TOOLS_PRE_SHR': ('float', '其他权益工具:优先股'),
        'OTH_NONCUR_ASSETS': ('float', '其他非流动资产'),
        'OTHER_ASSETS': ('float', '其他资产'),
        'OTHER_CUR_ASSETS': ('float', '其他流动资产'),
        'OTHER_CUR_LIAB': ('float', '其他流动负债'),
        'OTHER_DEBT_INV': ('float', '其他债权投资(元)'),
        'OTHER_EQUITY_INV': ('float', '其他权益工具投资(元)'),
        'OTHER_LIAB': ('float', '其他负债'),
        'OTHER_NONCUR_FIN_ASSETS': ('float', '其他非流动金融资产(元)'),
        'OTHER_NONCUR_LIAB': ('float', '其他非流动负债'),
        'OTHER_PAYABLE': ('float', '其他应付款'),
        'OTHER_PAYABLE_TOTAL': ('float', '其他应付款(合计)(元)'),
        'OTHER_RCV_TOTAL': ('float', '其他应收款(合计)（元）'),
        'OTHER_RECEIVABLE': ('float', '其他应收款'),
        'OTHER_SUSTAIN_BOND': ('float', '其他权益工具:永续债(元)'),
        'OUT_LOSS_RESV': ('float', '未决赔款准备金'),
        'PAYABLE': ('float', '应付款项'),
        'PAYABLE_FOR_REINSURER': ('float', '应付分保账款'),
        'PRECIOUS_METAL': ('float', '贵金属'),
        'PREPAYMENT': ('float', '预付款项'),
        'PROD_BIO_ASSETS': ('float', '生产性生物资产'),
        'RCV_CED_CLAIM_RESV': ('float', '应收分保未决赔款准备金'),
        'RCV_CED_LIFE_INSUR_RESV': ('float', '应收分保寿险责任准备金'),
        'RCV_CED_LT_HEALTH_INSUR_RESV': ('float', '应收分保长期健康险责任准备金'),
        'RCV_CED_UNEARNED_PREM_RESV': ('float', '应收分保未到期责任准备金'),
        'RCV_FINANCING': ('float', '应收款项融资'),
        'RCV_INV': ('float', '应收款项类投资'),
        'RECEIVABLE_PREM': ('float', '应收保费'),
        'RED_MON_CAP_FOR_SALE': ('float', '买入返售金融资产'),
        'REINSURANCE_ACC_RCV': ('float', '应收分保账款'),
        'RSRV_FUND_INSUR_CONT': ('float', '保险合同准备金'),
        'SELL_REPO_FIN_ASSETS': ('float', '卖出回购金融资产款'),
        'SERVICE_CHARGE_COMM_PAYABLE': ('float', '应付手续费及佣金'),
        'SETTLE_FUNDS': ('float', '结算备付金'),
        'SPE_ASSETS_BAL_DIFF': ('float', '资产差额(特殊报表科目)'),
        'SPE_CUR_ASSETS_DIFF': ('float', '流动资产差额(特殊报表科目)'),
        'SPE_CUR_LIAB_DIFF': ('float', '流动负债差额(特殊报表科目)'),
        'SPE_LIAB_BAL_DIFF': ('float', '负债差额(特殊报表科目)'),
        'SPE_LIAB_EQUITY_BAL_DIFF': ('float', '负债及股东权益差额(特殊报表项目)'),
        'SPE_NONCUR_ASSETS_DIFF': ('float', '非流动资产差额(特殊报表科目)'),
        'SPE_NONCUR_LIAB_DIFF': ('float', '非流动负债差额(特殊报表科目)'),
        'SPE_SHARE_EQUITY_BAL_DIFF': ('float', '股东权益差额(特殊报表科目)'),
        'SPECIAL_PAYABLE': ('float', '专项应付款'),
        'SPECIAL_RESV': ('float', '专项储备'),
        'ST_BONDS_PAYABLE': ('float', '应付短期债券'),
        'ST_BORROWING': ('float', '短期借款'),
        'ST_FIN_PAYABLE': ('float', '应付短期融资款'),
        'SUBR_RCV': ('float', '应收代位追偿款'),
        'SURPLUS_RESV': ('float', '盈余公积金'),
        'TAX_PAYABLE': ('float', '应交税费'),
        'TOT_ASSETS_BAL_DIFF': ('float', '资产差额(合计平衡项目)'),
        'TOT_CUR_ASSETS_DIFF': ('float', '流动资产差额(合计平衡项目)'),
        'TOT_CUR_LIAB_DIFF': ('float', '流动负债差额(合计平衡项目)'),
        'TOT_LIAB_BAL_DIFF': ('float', '负债差额(合计平衡项目)'),
        'TOT_LIAB_EQUITY_BAL_DIFF': ('float', '负债及股东权益差额(合计平衡项目)'),
        'TOT_NONCUR_ASSETS': ('float', '非流动资产合计'),
        'TOT_NONCUR_ASSETS_DIFF': ('float', '非流动资产差额(合计平衡项目)'),
        'TOT_NONCUR_LIAB_DIFF': ('float', '非流动负债差额(合计平衡项目)'),
        'TOT_SHARE': ('float', '期末总股本 单位（股）'),
        'TOT_SHARE_EQUITY_BAL_DIFF': ('float', '股东权益差额(合计平衡项目)'),
        'TOT_SHARE_EQUITY_EXCL_MIN_INT': ('float', '股东权益合计(不含少数股东权益)'),
        'TOT_SHARE_EQUITY_INCL_MIN_INT': ('float', '股东权益合计(含少数股东权益)'),
        'TOTAL_ASSETS': ('float', '资产总计'),
        'TOTAL_CUR_ASSETS': ('float', '流动资产合计'),
        'TOTAL_CUR_LIAB': ('float', '流动负债合计'),
        'TOTAL_LIAB': ('float', '负债合计'),
        'TOTAL_LIAB_SHARE_EQUITY': ('float', '负债及股东权益总计'),
        'TOTAL_NONCUR_LIAB': ('float', '非流动负债合计'),
        'TRADING_FIN_LIAB': ('float', '交易性金融负债'),
        'TRADING_FINASSETS': ('float', '交易性金融资产'),
        'UNAMORTIZED_EXP': ('float', '待摊费用'),
        'UNCONFIRMED_INV_LOSS': ('float', '未确认的投资损失'),
        'UNDISTRIBUTED_PRO': ('float', '未分配利润'),
        'UNEARNED_PREM_RESV': ('float', '未到期责任准备金'),
        'USE_RIGHT_ASSETS': ('float', '使用权资产'),
    },
    'cash_flow': {
        '__source__': '手册「cash_flow的字段说明」；列名与列序取自 wheel 的 columns_list（120 列）',
        'MARKET_CODE': ('str', '证券代码'),
        'SECURITY_NAME': ('str', '证券简称'),
        'STATEMENT_TYPE': ('str', '报表类型 参看报表类型代码表'),
        'REPORT_TYPE': ('str', '报告期名称 参看报告期名称'),
        'REPORTING_PERIOD': ('str', '报告期'),
        'ANN_DATE': ('str', '公告日期'),
        'ACTUAL_ANN_DATE': ('str', '实际公告日期'),
        'ABSORB_CASH_RECP_INV': ('double', '吸收投资收到的现金'),
        'AMORT_INTAN_ASSETS': ('double', '无形资产摊销'),
        'AMORT_LT_DEFERRED_EXP': ('double', '长期待摊费用摊销'),
        'BEG_BAL_CASH_CASH_EQU': ('double', '期初现金及现金等价物余额'),
        'CASH_END_BAL': ('double', '现金的期末余额'),
        'CASH_FOR_CHARGE': ('double', '支付手续费的现金'),
        'CASH_PAID_INSUR_POLICY': ('double', '支付保单红利的现金'),
        'CASH_PAID_INV': ('double', '投资支付的现金'),
        'CASH_PAID_PUR_CONST_FIOLTA': ('double', '购建固定资产、无形资产和其他长期资产支付的现金'),
        'CASH_PAY_CLAIMS_OIC': ('double', '支付原保险合同赔付款项的现金'),
        'CASH_PAY_DIST_DIV_PRO_INT': ('double', '分配股利、利润或偿付利息支付的现金'),
        'CASH_PAY_EMPLOYEE': ('double', '支付给职工以及为职工支付的现金'),
        'CASH_PAY_FOR_DEBT': ('double', '偿还债务支付的现金'),
        'CASH_PAY_GOODS_SERVICES': ('double', '购买商品、接受劳务支付的现金'),
        'CASH_RECE_BORROW': ('double', '取得借款收到的现金'),
        'CASH_RECE_ISSUE_BONDS': ('double', '发行债券收到的现金'),
        'CASH_RECP_INV_INCOME': ('double', '取得投资收益收到的现金'),
        'CASH_RECP_PREM_OIC': ('double', '收到原保险合同保费取得的现金'),
        'CASH_RECP_RECOV_INV': ('double', '收回投资收到的现金'),
        'CASH_RECP_SG_AND_RS': ('double', '销售商品、提供劳务收到的现金'),
        'COMP_TYPE_CODE': ('str', '公司类型代码1：非金融类2：银行 3：保险 4： 证券'),
        'CONV_CORP_BONDS_DUE_WITHIN_1Y': ('double', '一年内到期的可转换公司债券'),
        'CONV_DEBT_INTO_CAP': ('double', '债务转为资本'),
        'CREDIT_IMPAIR_LOSS': ('double', '信用减值损失'),
        'CURRENCY_CODE': ('str', '货币代码'),
        'DECR_DEFE_INC_TAX_ASSETS': ('double', '递延所得税资产减少'),
        'DECR_DEFERRED_EXPENSE': ('double', '待摊费用减少'),
        'DECR_INVENTORY': ('double', '存货的减少'),
        'DECR_OPERA_RECEIVABLE': ('double', '经营性应收项目的减少'),
        'DEPRE_FA_OGA_PBA': ('double', '固定资产折旧、油气资产折耗、生产性生物资产折旧'),
        'EFF_FX_FLUC_CASH': ('double', '汇率变动对现金的影响'),
        'END_BAL_CASH_CASH_EQU': ('double', '期末现金及现金等价物余额'),
        'FINANCIAL_EXP': ('double', '财务费用'),
        'FIXED_ASSETS_FIN_LEASE': ('double', '融资租入固定资产'),
        'FREE_CASH_FLOW': ('double', '企业自由现金流量'),
        'INCL_CASH_RECP_SAIMS': ('double', '其中:子公司吸收少数股东投资收到的现金'),
        'INCL_DIV_PRO_PAID_SMS': ('double', '其中:子公司支付给少数股东的股利、利润'),
        'INCR_ACCRUED_EXP': ('double', '预提费用增加'),
        'INCR_DEFE_INC_TAX_LIAB': ('double', '递延所得税负债增加'),
        'INCR_OPERA_PAYABLE': ('double', '经营性应付项目的增加'),
        'IND_NET_CASH_FLOWS_OPERA_ACT': ('double', '间接法 -经营活动产生的现金流量净额'),
        'IND_NET_INCR_CASH_AND_EQU': ('double', '间接法-现金及现金等价物净增加额'),
        'INV_LOSS': ('double', '投资损失'),
        'IS_CALCULATION': ('int', '是否计算报表'),
        'LESS_OPEN_BAL_CASH': ('double', '减:现金的期初余额'),
        'LESS_OPEN_BAL_CASH_EQU': ('double', '减:现金等价物的期初余额'),
        'LOSS_DISP_FIOLTA': ('double', '处置固定、无形资产和其他长期资产的损失'),
        'LOSS_FAIRVALUE_CHG': ('double', '公允价值变动损失'),
        'LOSS_FIXED_ASSETS': ('double', '固定资产报废损失'),
        'NET_CASH_FLOWS_FIN_ACT': ('double', '筹资活动产生的现金流量净额'),
        'NET_CASH_FLOWS_INV_ACT': ('double', '投资活动产生的现金流量净额'),
        'NET_CASH_FLOWS_OPERA_ACT': ('double', '经营活动产生的现金流量净额'),
        'NET_CASH_PAID_SOBU': ('double', '取得子公司及其他营业单位支付的现金净额'),
        'NET_CASH_REC_SEC': ('double', '代理买卖证券收到的现金净额'),
        'NET_CASH_RECP_DISP_FIOLTA': ('double', '处置固定资产、无形资产和其他长期资产收回的现金净额'),
        'NET_CASH_RECP_DISP_SOBU': ('double', '处置子公司及其他营业单位收到的现金净额'),
        'NET_CASH_RECP_REINSU_BUS': ('double', '收到再保业务现金净额'),
        'NET_INCR_BORR_FUND': ('double', '拆入资金净增加额'),
        'NET_INCR_BORR_OFI': ('double', '向其他金融机构拆入资金净增加额'),
        'NET_INCR_CASH_AND_CASH_EQU': ('double', '现金及现金等价物净增加额'),
        'NET_INCR_CUS_LOAN_ADV': ('double', '客户贷款及垫款净增加额'),
        'NET_INCR_DEP_CB_IB': ('double', '存放央行和同业款项净增加额'),
        'NET_INCR_DEP_CUS_AND_IB': ('double', '客户存款和同业存放款项净增加额'),
        'NET_INCR_DISMANTLE_CAP': ('double', '拆出资金净增加额'),
        'NET_INCR_DISP_FAAS': ('double', '处置可供出售金融资产净增加额'),
        'NET_INCR_DISP_TFA': ('double', '处置交易性金融资产净增加额'),
        'NET_INCR_INSURED_SAVE': ('double', '保户储金净增加额'),
        'NET_INCR_INT_AND_CHARGE': ('double', '收取利息和手续费净增加额'),
        'NET_INCR_LOANS_CENTRAL_BANK': ('double', '向中央银行借款净增加额'),
        'NET_INCR_PLEDGE_LOAN': ('double', '质押贷款净增加额'),
        'NET_INCR_REPU_BUS_FUND': ('double', '回购业务资金净增加额'),
        'NET_PROFIT': ('double', '净利润'),
        'OTH_CASH_PAY_INV_ACT': ('double', '支付其他与投资活动有关的现金'),
        'OTH_CASH_PAY_OPERA_ACT': ('double', '支付其他与经营活动有关的现金'),
        'OTH_CASH_RECP_INV_ACT': ('double', '收到其他与投资活动有关的现金'),
        'OTHER_ASSETS_IMPAIR_LOSS': ('double', '其他资产减值损失'),
        'OTHER_CASH_PAY_FIN_ACT': ('double', '支付其他与筹资活动有关的现金'),
        'OTHER_CASH_RECP_FIN_ACT': ('double', '收到其他与筹资活动有关的现金'),
        'OTHER_CASH_RECP_OPER_ACT': ('double', '收到其他与经营活动有关的现金'),
        'OTHERS': ('double', '其他（废弃）'),
        'PAY_ALL_TAX': ('double', '支付的各项税费'),
        'PLUS_ASSETS_DEPRE_PREP': ('double', '加:资产减值准备'),
        'PLUS_END_BAL_CASH_EQU': ('double', '加:现金等价物的期末余额'),
        'RECP_TAX_REFUND': ('double', '收到的税费返还'),
        'SPE_BAL_CASH_INFLOW_FIN_ACT': ('double', '筹资活动现金流入差额'),
        'SPE_BAL_CASH_INFLOW_INV_ACT': ('double', '投资活动现金流入差额'),
        'SPE_BAL_CASH_INFLOW_OPERA_ACT': ('double', '经营活动现金流入差额'),
        'SPE_BAL_CASH_OUTFLOW_FIN': ('double', '筹资活动现金流出差额'),
        'SPE_BAL_CASH_OUTFLOW_INV': ('double', '投资活动现金流出差额'),
        'SPE_BAL_CASH_OUTFLOW_OPERA': ('double', '经营活动现金流出差额'),
        'SPE_BAL_NETCASH_INC_DIFF_IND': ('double', '间接法-现金净增加额差额'),
        'SPE_BAL_NETCASH_INCR_DIFF': ('double', '现金净增加额差额'),
        'SPE_BAL_NETCASH_OPERA_IND': ('double', '间接法-经营活动现金流量净额差额'),
        'TOT_BAL_CASH_INFLOW_FIN_ACT': ('double', '筹资活动现金流入差额'),
        'TOT_BAL_CASH_INFLOW_INV_ACT': ('double', '投资活动现金流入差额'),
        'TOT_BAL_CASH_INFLOW_OPERA_ACT': ('double', '经营活动现金流入差额'),
        'TOT_BAL_CASH_OUTFLOW_FIN': ('double', '筹资活动现金流出差额'),
        'TOT_BAL_CASH_OUTFLOW_INV': ('double', '投资活动现金流出差额'),
        'TOT_BAL_CASH_OUTFLOW_OPERA': ('double', '经营活动现金流出差额'),
        'TOT_BAL_NETCASH_FLOW_FIN': ('double', '筹资活动产生的现金流量净额差额'),
        'TOT_BAL_NETCASH_FLOW_INV': ('double', '投资活动产生的现金流量净额差额'),
        'TOT_BAL_NETCASH_FLOW_OPERA': ('double', '经营活动产生的现金流量净额差额'),
        'TOT_BAL_NETCASH_INC_DIFF_IND': ('double', '间接法-现金净增加额差额'),
        'TOT_BAL_NETCASH_INCR_DIFF': ('double', '现金净增加额差额'),
        'TOT_BAL_NETCASH_OPERA_IND': ('double', '间接法-经营活动现金流量净额差额'),
        'TOT_CASH_INFLOW_FIN_ACT': ('double', '筹资活动现金流入小计'),
        'TOT_CASH_INFLOW_INV_ACT': ('double', '投资活动现金流入小计'),
        'TOT_CASH_INFLOW_OPER_ACT': ('double', '经营活动现金流入小计'),
        'TOT_CASH_OUTFLOW_FIN_ACT': ('double', '筹资活动现金流出小计'),
        'TOT_CASH_OUTFLOW_INV_ACT': ('double', '投资活动现金流出小计'),
        'TOT_CASH_OUTFLOW_OPERA_ACT': ('double', '经营活动现金流出小计'),
        'UNCONFIRMED_INV_LOSS': ('double', '未确认投资损失'),
        'USE_RIGHT_ASSET_DEP': ('double', '使用权资产折旧'),
    },
    'income': {
        '__source__': '手册「income的字段说明」；列名与列序取自 wheel 的 columns_list（111 列）',
        'MARKET_CODE': ('str', '证券代码'),
        'SECURITY_NAME': ('str', '证券简称'),
        'STATEMENT_TYPE': ('str', '报表类型 参看报表类型代码表'),
        'REPORT_TYPE': ('str', '报告期名称 参看报告期名称'),
        'REPORTING_PERIOD': ('str', '报告期'),
        'ANN_DATE': ('str', '公告日期'),
        'ACTUAL_ANN_DATE': ('str', '实际公告日期'),
        'ADJ_PREV_YEAR_LOSS_GAIN': ('', '🔴 手册的字段表里没有这一列（wheel 的 columns_list 里有，说明接口会返回它）'),
        'AMORT_COST_FIN_ASSETS_EAR': ('float', '以摊余成本计量的金融资产终止确认收益'),
        'BASIC_EPS': ('float', '基本每股收益'),
        'BEG_UNDISTRIBUTED_PRO': ('float', '年初未分配利润'),
        'CAPITALIZED_COM_STOCK_DIV': ('float', '转作股本的普通股股利'),
        'COMMENTS': ('str', '备注'),
        'COMMON_STOCK_DIV_PAYABLE': ('float', '应付普通股股利'),
        'COMP_TYPE_CODE': ('str', '公司类型代码 1：非金融类2： 银行3：保险 4：证券'),
        'CONTINUED_NET_OPERA_PRO': ('float', '持续经营净利润'),
        'CREDIT_IMPAIR_LOSS': ('float', '信用减值损失'),
        'CURRENCY_CODE': ('str', '货币代码'),
        'DILUTED_EPS': ('float', '稀释每股收益'),
        'DISTRIBUTIVE_PRO': ('float', '可分配利润'),
        'DISTRIBUTIVE_PRO_SHAREHOLDER': ('float', '可供股东分配的利润'),
        'DIV_EXP_INSUR': ('float', '保户红利支出'),
        'EBIT': ('float', '息税前利润 正向法'),
        'EBITDA': ('float', '息税折旧摊销前利润'),
        'EMPLOYEE_WELFARE': ('float', '职工奖金福利'),
        'END_NET_OPERA_PRO': ('float', '终止经营净利润'),
        'EXT_INSUR_CONT_RSRV': ('float', '提取保险责任准备金'),
        'EXT_UNEARNED_PREM_RES': ('float', '提取未到期责任准备金'),
        'FIN_EXP_INT_EXP': ('float', '财务费用 :利息费用'),
        'FIN_EXP_INT_INC': ('float', '财务费用 :利息收入'),
        'GAIN_DISPOSAL_ASSETS': ('float', '资产处置收益'),
        'HANDLING_CHRG_COMM_FEE': ('float', '手续费及佣金收入'),
        'INCL_INC_INV_JV_ENTP': ('float', '其中 :对联营企业和合营企业的投资收益'),
        'INCL_LESS_LOSS_DISP_NCUR_ASSET': ('float', '其中:减:非流动资产处置净损失'),
        'INCL_REINSUR_PREM_INC': ('float', '其中:分保费收入'),
        'INCOME_TAX': ('float', '所得税'),
        'INSUR_EXP': ('float', '保险业务支出'),
        'INSUR_PREM': ('float', '已赚保费'),
        'INTEREST_INC': ('float', '利息收入'),
        'IS_CALCULATION': ('float', '是否计算报表'),
        'LESS_ADMIN_EXP': ('float', '减:管理费用'),
        'LESS_AMORT_COMPEN_EXP': ('float', '减:摊回赔付支出'),
        'LESS_AMORT_INSUR_CONT_RSRV': ('float', '减:摊回保险责任准备金'),
        'LESS_AMORT_REINSUR_EXP': ('float', '减:摊回分保费用'),
        'LESS_ASSETS_IMPAIR_LOSS': ('float', '减:资产减值损失'),
        'LESS_BUS_TAX_SURCHARGE': ('float', '减:营业税金及附加'),
        'LESS_FIN_EXP': ('float', '减:财务费用'),
        'LESS_HANDLING_CHRG_COMM_FEE': ('float', '减:手续费及佣金支出'),
        'LESS_INTEREST_EXP': ('float', '减:利息支出'),
        'LESS_NON_OPERA_EXP': ('float', '减:营业外支出'),
        'LESS_OPERA_COST': ('float', '减:营业成本'),
        'LESS_REINSUR_PREM': ('float', '减:分出保费'),
        'LESS_SELLING_EXP': ('float', '减:销售费用'),
        'MIN_INT_INC': ('float', '少数股东损益'),
        'NET_EXPOSURE_HEDGING_GAIN': ('float', '净敞口套期收益'),
        'NET_HANDLING_CHRG_COMM_FEE': ('float', '手续费及佣金净收入'),
        'NET_INC_EC_ASSET_MGMT_BUS': ('float', '受托客户资产管理业务净收入'),
        'NET_INC_SEC_BROK_BUS': ('float', '代理买卖证券业务净收入'),
        'NET_INC_SEC_UW_BUS': ('float', '证券承销业务净收入'),
        'NET_INTEREST_INC': ('float', '利息净收入'),
        'NET_PRO_AFTER_DED_NR_GL': ('float', '扣除非经常性损益后净利润（扣除少数股东损益）'),
        'NET_PRO_AFTER_DED_NR_GL_COR': ('float', '扣除非经常性损益后的净利润 (财务重要指标(更正前))'),
        'NET_PRO_EXCL_MIN_INT_INC': ('float', '净利润 (不含少数股东损益)'),
        'NET_PRO_INCL_MIN_INT_INC': ('float', '净利润 (含少数股东损益)'),
        'NET_PRO_UNDER_INT_ACC_STA': ('float', '国际会计准则净利润'),
        'OPERA_EXP': ('float', '营业支出'),
        'OPERA_PROFIT': ('float', '营业利润'),
        'OPERA_REV': ('float', '营业收入'),
        'OTH_ASSETS_IMPAIR_LOSS': ('float', '其他资产减值损失'),
        'OTH_BUS_COST': ('float', '其他业务成本'),
        'OTH_BUS_INC': ('float', '其他业务收入'),
        'OTH_COMPRE_INC': ('float', '其他综合收益'),
        'OTH_INCOME': ('float', '其他收益'),
        'OTH_NET_OPERA_INC': ('float', '其他经营净收益'),
        'PLUS_NET_FX_INC': ('float', '加:汇兑净收益'),
        'PLUS_NET_GAIN_CHG_FV': ('float', '加:公允价值变动净收益'),
        'PLUS_NET_INV_INC': ('float', '加:投资净收益'),
        'PLUS_NON_OPERA_REV': ('float', '加:营业外收入'),
        'PLUS_OTH_NET_BUS_INC': ('float', '加:其他业务净收益'),
        'PREFERRED_SHARE_DIV_PAYABLE': ('float', '应付优先股股利'),
        'PREM_BUS_INC': ('float', '保费业务收入'),
        'RD_EXP': ('float', '研发费用'),
        'REINSURANCE_EXP': ('float', '分保费用REPORTING_PERI'),
        'SPE_BAL_NET_PRO_MARG': ('float', '净利润差额 (特殊报表科目)'),
        'SPE_BAL_OPERA_PRO_MARG': ('float', '营业利润差额 (特殊报表科目)'),
        'SPE_BAL_TOT_OPERA_COST_DIF': ('float', '营业总成本差额(特殊报表科目)'),
        'SPE_BAL_TOT_OPERA_INC_DIF': ('float', '营业总收入差额(特殊报表科目)'),
        'SPE_BAL_TOT_PRO_MARG': ('float', '利润总额差额 (特殊报表科目)'),
        'SPE_TOT_OPERA_COST_DIF_STATE': ('str', '营业总成本差额说明(特殊报表科目)'),
        'SPE_TOT_OPERA_INC_DIF_STATE': ('str', '营业总收入差额说明(特殊报表科目)'),
        'SURR_VALUE': ('float', '退保金'),
        'TOT_BAL_NET_PRO_MARG': ('float', '净利润差额 (合计平衡项目)'),
        'TOT_BAL_OPERA_PRO_MARG': ('float', '营业利润差额 (合计平衡项目)'),
        'TOT_BAL_TOT_PRO_MARG': ('float', '利润总额差额 (合计平衡项目)'),
        'TOT_COMPEN_EXP': ('float', '赔付总支出'),
        'TOT_COMPRE_INC': ('float', '综合收益总额'),
        'TOT_COMPRE_INC_MIN_SHARE': ('float', '综合收益总额 (少数股东)'),
        'TOT_COMPRE_INC_PARENT_COMP': ('float', '综合收益总额 (母公司)'),
        'TOT_OPERA_COST': ('float', '营业总成本'),
        'TOT_OPERA_COST2': ('float', '营业总成本 2'),
        'TOT_OPERA_REV': ('float', '营业总收入'),
        'TOTAL_PROFIT': ('float', '利润总额'),
        'TRANSFER_HOUSING_REVO_FUNDS': ('float', '住房周转金转入'),
        'TRANSFER_OTHERS': ('float', '其他转入'),
        'TRANSFER_SURPLUS_RESERVE': ('float', '盈余公积转入'),
        'UNCONFIRMED_INV_LOSS': ('float', '未确认投资损失'),
        'WITHDRAW_ANY_SURPLUS_RESV': ('float', '提取任意盈余公积金'),
        'WITHDRAW_ENT_DEVELOP_FUND': ('float', '提取企业发展基金'),
        'WITHDRAW_LEG_PUB_WEL_FUND': ('float', '提取法定公益金'),
        'WITHDRAW_LEG_SURPLUS': ('float', '提取法定盈余公积'),
        'WITHDRAW_RESV_FUND': ('float', '提取储备基金'),
    },
    'profit_express': {
        '__source__': '手册「profit_express的字段说明」；列名与列序取自 wheel 的 columns_list（33 列）',
        'MARKET_CODE': ('str', '证券代码'),
        'REPORTING_PERIOD': ('str', '报告期 报告内容记录的截止时间点，报告成果的时期'),
        'ANN_DATE': ('str', '公告日期 公告发布当天的日期；有多个阶段的事件，首次披露该事件的日期'),
        'ACTUAL_ANN_DATE': ('str', '实际公告日期实际数据来源公告的日期；更正发生公告的日期'),
        'TOTAL_ASSETS': ('float64', '总资产(元) 指经济实体拥有或控制的能带来经济利益的全部资产'),
        'NET_PRO_EXCL_MIN_INT_INC': ('float64', '净利润(元) 企业合并净利润中归属于母公司股东所有的那部分利润'),
        'TOT_OPERA_REV': ('float64', '营业总收入(元)企业从事销售商品、提供劳务和让渡资产使用权等日常业务过程形成的经济利益的总流入'),
        'TOTAL_PROFIT': ('float64', '利润总额(元)企业一定时期内的纯收入扣除应交纳后的余额'),
        'OPERA_PROFIT': ('float64', '营业利润(元)企业在其全部销售业务中实现的利润'),
        'EPS_BASIC': ('float64', '每股收益 -基本(元)企业按照属于普通股股东的当期净利润，除以发行在外普通股的加权平均数计算得到的每股收益'),
        'TOT_SHARE_EQU_EXCL_MIN_INT': ('float64', '股东权益合计 (不含少数股东权益)(元)公司集团的所有者权益中归属于母公司所有者权益的部分'),
        'IS_AUDIT': ('float64', '是否审计 1:是 0：否'),
        'ROE_WEIGHTED': ('float64', '净资产收益率-加权(%)经营期间净资产赚取利润的结果的一个动态指标，反应企业净资产创造利润的能力'),
        'LAST_YEAR_REVISED_NET_PRO': ('float64', '去年同期修正后净利润元'),
        'PERFORMANCE_SUMMARY': ('str', '业绩简要说明针对业绩快报的简单说明'),
        'NET_ASSET_PS': ('float64', '每股净资产 元'),
        'MEMO': ('str', '备注 附加的注解说明'),
        'YOY_GR_GROSS_PRO': ('float64', '同比增长率:营业利润%'),
        'YOY_GR_GROSS_REV': ('float64', '同比增长率:营业总收入%'),
        'YOY_GR_NET_PROFIT_PARENT': ('float64', '同比增长率:归属母公司股东的净利润%'),
        'YOY_GR_TOT_PRO': ('float64', '同比增长率:利润总额%'),
        'YOY_ID_WAROE': ('float64', '同比增减:加权平均净资产收益率%'),
        'YOY_GR_EPS_BASIC': ('float64', '同比增长率:基本每股收益%'),
        'GROWTH_RATE_EQUITY': ('float64', '比年初增长率:归属母公司的股东权益%'),
        'GROWTH_RATE_ASSETS': ('float64', '比年初增长率:总资产%'),
        'GROWTH_RATE_NAPS': ('float64', '比年初增长率:归属于母公司股东的每股净资产%'),
        'LAST_YEAR_TOT_OPERA_REV': ('float64', '去年同期营业总收入元'),
        'LAST_YEAR_TOTAL_PROFIT': ('float64', '去年同期利润总额元'),
        'LAST_YEAR_OPERA_PRO': ('float64', '去年同期营业利润元'),
        'LAST_YEAR_EPS_DILUTED': ('float64', '去年同期每股收益元'),
        'LAST_YEAR_NET_PROFIT': ('float64', '去年同期净利润元'),
        'INITIAL_NET_ASSET_PS': ('float64', '期初每股净资产元'),
        'INITIAL_NET_ASSETS': ('float64', '期初净资产 元'),
    },
    'profit_notice': {
        '__source__': '手册「profit_notice的字段说明」；列名与列序取自 wheel 的 columns_list（15 列）',
        'MARKET_CODE': ('str', '证券代码'),
        'SECURITY_NAME': ('str', '证券简称'),
        'P_TYPECODE': ('str', '业绩预告类型代码1：不确定2：略减3：略增4：扭亏5：其他6：首亏7：续亏8：续盈9：预减10：预增11：持平'),
        'REPORTING_PERIOD': ('str', '报告期 分为年度、半年度、季度'),
        'ANN_DATE': ('str', '公告日期 公告发布当天的日期'),
        'P_CHANGE_MAX': ('float64', '预告净利润变动幅度上限（%）对于净利润金额同比变动幅度预计的最高值'),
        'P_CHANGE_MIN': ('float64', '预告净利润变动幅度下限（%）对于净利润金额同比变动幅度预计的最低值'),
        'NET_PROFIT_MAX': ('float64', '预告净利润上限（万元）对于净利润金额预计的最高值'),
        'NET_PROFIT_MIN': ('float64', '预告净利润下限（万元）对于净利润金额预计的最低值'),
        'FIRST_ANN_DATE': ('str', '首次公告日 首次披露本报告期业绩预告内容的公告日期'),
        'P_NUMBER': ('float64', '公布次数 同一报告期的业 绩预告公告的披露次数'),
        'P_REASON': ('str', '业绩变动原因'),
        'P_SUMMARY': ('str', '业绩预告摘要'),
        'P_NET_PARENT_FIRM': ('float64', '上年同期归母净利润业绩预告中直接公布的上年同期归母净利润'),
        'REPORT_TYPE': ('str', '报告期名称 参看报告期名称'),
    },
    'share_holder': {
        '__source__': '手册「share_holder的字段说明」；列名与列序取自 wheel 的 columns_list（11 列）',
        'ANN_DATE': ('str', '公告日期,'),
        'MARKET_CODE': ('str', '证券代码'),
        'HOLDER_ENDDATE': ('str', '到期日期'),
        'HOLDER_TYPE': ('int', '股东类别 10:十大股东20:流通股前十大股东'),
        'QTY_NUM': ('int', '持股量序号'),
        'HOLDER_NAME': ('str', '股东名称'),
        'HOLDER_HOLDER_CATEGORY': ('int', '股东性质 1：个人 2：公司'),
        'HOLDER_QUANTITY': ('float', '持股数（股）'),
        'HOLDER_PCT': ('float', '持股比例（%）,'),
        'HOLDER_SHARECATEGORYNAME': ('str', '股份类型 当 HOLDER_TYPE为 20:流通股前十大股东时，全部为‘A FloatHolder’'),
        'FLOAT_QTY': ('float', '流通股数量'),
    },
    'holder_num': {
        '__source__': '手册「holder_num的字段说明」；列名与列序取自 wheel 的 columns_list（5 列）',
        'MARKET_CODE': ('string', '证券代码'),
        'ANN_DT': ('string', '公告日期'),
        'HOLDER_ENDDATE': ('string', '股东户数统计的截止日期'),
        'HOLDER_NUM': ('float', 'A 股股东户数'),
        'HOLDER_TOTAL_NUM': ('float', 'A 股、B 股、H 股、境外股的总户数'),
    },
    'equity_structure': {
        '__source__': '手册「equity_structure的字段说明」；列名与列序取自 wheel 的 columns_list（54 列）',
        'MARKET_CODE': ('string', '证券代码'),
        'ANN_DATE': ('string', '公告日期'),
        'CHANGE_DATE': ('string', '变动日期注：股票分红送转股时的红股上市日;股票增发时的新股上市日'),
        'SHARE_CHANGE_REASON_STR': ('string', '股本变动原因描述'),
        'EX_CHANGE_DATE': ('string', '除权日期 股票分红送转股时的除权日 ;股票增发时的登记日'),
        'CURRENT_SIGN': ('int', '最新标志 1:是 0:否'),
        'IS_VALID': ('int', '是否有效用来区分除权日相同时，是否为公司公告公布的最新股份数1:是 0:否'),
        'TOT_SHARE': ('float', '总股本(万股)'),
        'FLOAT_SHARE': ('float', '流通股(万股)'),
        'FLOAT_A_SHARE': ('float', '流通 A股(万股)'),
        'FLOAT_B_SHARE': ('float', '流通 B 股(万股)'),
        'FLOAT_HK_SHARE': ('float', '香港流通股(万股)'),
        'FLOAT_OS_SHARE': ('float', '海外流通股(万股)'),
        'TOT_TRADABLE_SHARE': ('float', '流通股合计'),
        'RTD_A_SHARE_INST': ('float', '限售 A股(其他内资持股:机构配售股)'),
        'RTD_A_SHARE_DOMESNP': ('float', '限售 A股(其他内资持股:境内自然人持股)'),
        'RTD_SHARE_SENIOR': ('float', '限售股份 (高管持股)(万股)'),
        'RTD_A_SHARE_FOREIGN': ('float', '限售 A 股(外资持股)'),
        'RTD_A_SHARE_FORJUR': ('float', '限售 A股(境外法人持股)'),
        'RTD_A_SHARE_FORNP': ('float', '限售 A股(境外自然人持股)'),
        'RESTRICTED_B_SHARE': ('float', '限售 B 股(万股)'),
        'OTHER_RTD_SHARE': ('float', '其他限售股'),
        'NON_TRADABLE_SHARE': ('float', '非流通股'),
        'NTRD_SHARE_STATE_PCT': ('float', '非流通股(国有股)'),
        'NTRD_SHARE_STATE': ('float', '非流通股(国家股)'),
        'NTRD_SHARE_STATEJUR': ('float', '非流通股(国有法人股)'),
        'NTRD_SHARE_DOMESJUR': ('float', '非流通股(境内法人股)'),
        'NTRD_SHARE_DOMES_INITIATOR': ('float', '非流通股(境内法人股:境内发起人股)'),
        'NTRD_SHARE_IPOJURIS': ('float', '非流通股(境内法人股:募集法人股)'),
        'NTRD_SHARE_GENJURIS': ('float', '非流通股(境内法人股:一般法人股)'),
        'NTRD_SHARE_STRA_INVESTOR': ('float', '非流通股(境内法人股 :战略投资者持股)'),
        'NTRD_SHARE_FUND': ('float', '非流通股(境内法人股:基金持股)'),
        'NTRD_SHARE_NAT': ('float', '非流通股 (自然人股)'),
        'TRAN_SHARE': ('float', '转配股(万股)'),
        'FLOAT_SHARE_SENIOR': ('float', '流通股(高管持股)'),
        'SHARE_INEMP': ('float', '内部职工股(万股)'),
        'PREFERRED_SHARE': ('float', '优先股(万股)'),
        'NTRD_SHARE_NLIST_FRGN': ('float', '非流通股(非上市外资股)'),
        'STAQ_SHARE': ('float', 'STAQ股(万股)'),
        'NET_SHARE': ('float', 'NET股(万股)'),
        'SHARE_CHANGE_REASON': ('string', '股本变动原因'),
        'TOT_A_SHARE': ('float', 'A 股合计'),
        'TOT_B_SHARE': ('float', 'B 股合计'),
        'OTCA_SHARE': ('float', '三板 A股'),
        'OTCB_SHARE': ('float', '三板 B 股'),
        'TOT_OTC_SHARE': ('float', '三板合计'),
        'SHARE_HK': ('float', '香港上市股'),
        'PRE_NON_TRADABLE_SHARE': ('float', '股改前非流通股'),
        'RESTRICTED_A_SHARE': ('float', '限售 A股(万股)'),
        'RTD_A_SHARE_STATE': ('float', '限售 A 股(国家持股)'),
        'RTD_A_SHARE_STATEJUR': ('float', '限售 A股(国有法人持股)'),
        'RTD_A_SHARE_OTHER_DOMES': ('float', '限售 A股(其他内资持股)'),
        'RTD_A_SHARE_OTHER_DOMESJUR': ('float', '限售 A股(其他内资持股 :境内法人持股)'),
        'TOT_RESTRICTED_SHARE': ('float', '限售股合计'),
    },
    'equity_pledge_freeze': {
        '__source__': '手册「equity_pledge_freeze的字段说明」；列名与列序取自 wheel 的 columns_list（18 列）',
        'MARKET_CODE': ('string', '证券代码'),
        'ANN_DATE': ('string', '公告日期'),
        'HOLDER_NAME': ('string', '股东名称'),
        'HOLDER_TYPE_CODE': ('int', '股东类型代码 2:公司 3:个人'),
        'FRO_SHARES': ('float', '本次冻结 /质押股数'),
        'BEGIN_DATE': ('string', '冻结/质押起始日'),
        'END_DATE': ('string', '解冻/解押日期'),
        'IS_DISFROZEN': ('int', '是否质押或解冻 1:是 0:否'),
        'FROZEN_INSTITUTION': ('string', '执行冻结机构 /质权方'),
        'FREEZE_TYPE': ('int', '冻结/质押类型 1:质押 2:司法 3:质押式回购'),
        'TOTAL_HOLDING_SHR': ('float', '持股总数（万股）'),
        'FRO_SHR_TO_TOTAL_HOLDING_RATIO': ('float', '本次冻结 /质押占所持股比例'),
        'FRO_SHR_TO_TOTAL_RATIO': ('float', '本次冻结 /质押占总股本比例'),
        'TOTAL_PLEDGE_SHR': ('float', '累计冻结 /质押股数'),
        'TOTAL_HOLDING_SHR_RATIO': ('float', '持股总数占公司总股本比例'),
        'IS_EQUITY_PLEDGE_REPO': ('int', '是否股权质押回购 1:是 0:否'),
        'DISFROZEN_TIME': ('string', '解压或解冻日期'),
        'SHR_CATEGORY_CODE': ('int', '股份性质类别代码 1:法人股 2:个人股 3:国有股 4:国有股,法人股 5:流通股 6:流通股,限售流通股 7:外资股 8:限售流通股 9: 优先股'),
    },
    'equity_restricted': {
        '__source__': '手册「equity_restricted的字段说明」；列名与列序取自 wheel 的 columns_list（8 列）',
        'MARKET_CODE': ('string', '证券代码'),
        'LIST_DATE': ('string', '解禁日期'),
        'SHARE_RATIO': ('float', '解禁股占总股本比(%)'),
        'SHARE_LST_TYPE_NAME': ('string', '解禁股份类型名称'),
        'SHARE_LST': ('int', '解禁数量（股）'),
        'SHARE_LST_IS_ANN': ('int', '上市数量是否公布值 0：否，为预测值 1: 是, 为实际公布值'),
        'CLOSE_PRICE': ('float', '前日收盘价（元）'),
        'SHARE_LST_MARKET_VALUE': ('float', '解禁市值（元） SHARE_LST*CLOSE_PRICE'),
    },
    'dividend': {
        '__source__': '手册「dividend的字段说明」；列名与列序取自 wheel 的 columns_list（24 列）',
        'MARKET_CODE': ('string', '证券代码'),
        'DIV_PROGRESS': ('string', '方案进度 参看股票分红进度代码表'),
        'DVD_PER_SHARE_STK': ('float', '每股送转'),
        'DVD_PER_SHARE_PRE_TAX_CASH': ('float', '每股派息(税前)(元)'),
        'DVD_PER_SHARE_AFTER_TAX_CASH': ('float', '每股派息(税后)(元)'),
        'DATE_EQY_RECORD': ('string', '股权登记日'),
        'DATE_EX': ('string', '除权除息日'),
        'DATE_DVD_PAYOUT': ('string', '派息日'),
        'LISTINGDATE_OF_DVD_SHR': ('string', '红股上市日'),
        'DIV_PRELANDATE': ('string', '预案公告日 董事会预案公告日期'),
        'DIV_SMTGDATE': ('string', '股东大会公告日'),
        'DATE_DVD_ANN': ('string', '分红实施公告日'),
        'DIV_BASEDATE': ('string', '基准日期'),
        'DIV_BASESHARE': ('float', '基准股本(万股)'),
        'CURRENCY_CODE': ('string', '货币代码'),
        'ANN_DATE': ('string', '公告日期'),
        'IS_CHANGED': ('int', '方案是否变更 1：有变更过 0：未变更'),
        'REPORT_PERIOD': ('string', '分红年度'),
        'DIV_CHANGE': ('string', '方案变更说明'),
        'DIV_BONUSRATE': ('float', '每股送股比例'),
        'DIV_CONVERSEDRATE': ('float', '每股转增比例'),
        'REMARK': ('string', '备注'),
        'DIV_PREANN_DATE': ('string', '预案预披露公告日 股东提议的公告日期'),
        'DIV_TARGET': ('string', '分红对象'),
    },
    'right_issue': {
        '__source__': '手册「right_issue的字段说明」；列名与列序取自 wheel 的 columns_list（30 列）',
        'MARKET_CODE': ('string', '证券代码'),
        'PROGRESS': ('int', '方案进度 参看股票配股进度代码表'),
        'PRICE': ('double', '配股价格(元)'),
        'RATIO': ('double', '配股比例'),
        'AMT_PLAN': ('double', '配股计划数量(万股)'),
        'AMT_REAL': ('double', '配股实际数量(万股)'),
        'COLLECTION_FUND': ('double', '募集资金(元)'),
        'SHAREB_REG_DATE': ('string', '股权登记日'),
        'EX_DIVIDEND_DATE': ('string', '除权日'),
        'LISTED_DATE': ('string', '配股上市日'),
        'PAY_START_DATE': ('string', '缴款起始日'),
        'PAY_END_DATE': ('string', '缴款终止日'),
        'PREPLAN_DATE': ('string', '预案公告日'),
        'SMTG_ANN_DATE': ('string', '股东大会公告日'),
        'PASS_DATE': ('string', '发审委通过公告日'),
        'APPROVED_DATE': ('string', '证监会核准公告日'),
        'EXECUTE_DATE': ('string', '配股实施公告日'),
        'RESULT_DATE': ('string', '配股结果公告日'),
        'LIST_ANN_DATE': ('string', '上市公告日'),
        'GUARANTOR': ('string', '基准年度'),
        'GUARTYPE': ('double', '基准股本(万股)'),
        'RIGHTSISSUE_CODE': ('string', '配售代码'),
        'ANN_DATE': ('string', '公告日期'),
        'RIGHTSISSUE_YEAR': ('string', '配股年度'),
        'RIGHTSISSUE_DESC': ('string', '配股说明'),
        'RIGHTSISSUE_NAME': ('string', '配股简称'),
        'RATIO_DENOMINATOR': ('double', '配股比例分母'),
        'RATIO_MOLECULAR': ('double', '配股比例分子'),
        'SUBS_METHOD': ('string', '认购方式'),
        'EXPECTED_FUND_RAISING': ('double', '预计募集资金(元)'),
    },
    'margin_summary': {
        '__source__': '手册「margin_summary的字段说明」；列名与列序取自 wheel 的 columns_list（8 列）',
        'TRADE_DATE': ('string', '交易日期'),
        'EXCHANGE': ('', '🔴 手册的字段表里没有这一列（wheel 的 columns_list 里有，说明接口会返回它）'),
        'SUM_BORROW_MONEY_BALANCE': ('float', '融资余额(元)'),
        'SUM_PURCH_WITH_BORROW_MONEY': ('float', '融资买入额(元)'),
        'SUM_REPAYMENT_OF_BORROW_MONEY': ('float', '融资偿还额(元)'),
        'SUM_SEC_LENDING_BALANCE': ('float', '融券余额(元)'),
        'SUM_SALES_OF_BORROWED_SEC': ('int', '融券卖出量(股,份,手)'),
        'SUM_MARGIN_TRADE_BALANCE': ('float', '融资融券余额(元)'),
    },
    'margin_detail': {
        '__source__': '手册「margin_detail的字段说明」；列名与列序取自 wheel 的 columns_list（10 列）',
        'MARKET_CODE': ('string', '证券代码'),
        'TRADE_DATE': ('string', '交易日期'),
        'BORROW_MONEY_BALANCE': ('float', '融资余额(元)'),
        'PURCH_WITH_BORROW_MONEY': ('float', '融资买入额(元)'),
        'REPAYMENT_OF_BORROW_MONEY': ('float', '融资偿还额(元)'),
        'SEC_LENDING_BALANCE': ('float', '融券余额(元)'),
        'SALES_OF_BORROWED_SEC': ('int', '融券卖出量(股,份,手)'),
        'REPAYMENT_OF_BORROW_SEC': ('int', '融券偿还量(股,份,手)'),
        'SEC_LENDING_BALANCE_VOL': ('int', '融券余量(股,份,手)'),
        'MARGIN_TRADE_BALANCE': ('float', '融资融券余额(元)'),
    },
    'etf_pcf_info': {
        '__source__': '手册「etf_pcf_info的字段说明」；列名与列序取自 wheel 的 columns_list（25 列）',
        'creation_redemption_unit': ('int', '每个篮子对应的ETF份数'),
        'max_cash_ratio': ('string', '最大现金替代比例'),
        'publish': ('string', '是否发布 IOPV Y=是,N=否'),
        'creation': ('string', '是否允许申购 Y=是,N=否(仅深圳有效)'),
        'redemption': ('string', '是否允许赎回 Y=是,N=否(仅深圳有效)'),
        'creation_redemption_switch': ('string', '申购赎回切换 (仅上海有效 ,0 -不允许申购 /赎回 ,1 -申购和赎回皆允许,2-仅允许申购 ,3-仅允许赎回)'),
        'record_num': ('int', '深市成份证券数目'),
        'total_record_num': ('int', '所有成份证券数量'),
        'estimate_cash_component': ('int', '预估现金差额'),
        'trading_day': ('int', '当前交易日 (格式:YYYYMMDD)'),
        'pre_trading_day': ('int', '前一交易日 (格式:YYYYMMDD)'),
        'cash_component': ('int', '前一日现金差额'),
        'nav_per_cu': ('int', '前一日最小申赎单位净值'),
        'nav': ('int', '前一日基金份额净值'),
        'symbol': ('string', '基金名称 仅深圳有效'),
        'fund_management_company': ('string', '基金公司名称 仅深圳有效'),
        'underlying_security_id': ('string', '拟合指数代码 仅深圳有效'),
        'underlying_security_id_source': ('string', '拟合指数市场 参考 Market，仅深圳有效'),
        'dividend_per_cu': ('int', '红利金额'),
        'creation_limit': ('int', '累计申购总额限制为 0 表示没有限制(仅深圳有效)'),
        'redemption_limit': ('int', '累计赎回总额限制0 表示没有限制(仅深圳有效)'),
        'creation_limit_per_user': ('int', '单个账户累计申购总额限制0 表示没有限制(仅深圳有效)'),
        'redemption_limit_per_user': ('int', '单个账户累计赎回总额限制0 表示没有限制(仅深圳有效)'),
        'net_creation_limit': ('int', '净申购总额限制 0 表示没有限制(仅深圳有效)'),
        'net_redemption_limit': ('int', '净赎回总额限制 0 表示没有限制(仅深圳有效)'),
    },
    'etf_pcf_constituent': {
        '__source__': '手册「etf_pcf_constituent的字段说明」；列名与列序取自 wheel 的 columns_list（9 列）',
        'underlying_symbol': ('string', '成份证券简称'),
        'component_share': ('int', '成份证券数量'),
        'substitute_flag': ('string', '现金替代标志//**深圳现金替代标志* //0=禁止现金替代 (必须有证券 ),1=可以进行现金替代 (先用证券,证券不足时差额部分用现金替代),2=必须用现金替代//**上海现金替代标志*//ETF 公告文件1.0 版格式//0 –沪市不可被替代, 1 – 沪市可以被替代, 2 – 沪市必须被替代, 3 – 深市退补现金替代, 4 – 深市必须现金替代//5 – 非沪深市场成份证券退补现金替代 (不适用于跨沪深港 ETF 产品), 6 – 非沪深市场成份证券必须现金替代 (不适用于跨沪深港 ETF 产品)//ETF 公告文件2.1 版格式//0 –沪市不可被替代, 1 – 沪市可以被替代, 2 – 沪市必须被替代, 3 – 深市退补现金替代, 4 – 深市必须现金替代//5 – 非沪深市场成份证券退补现金替代 (不适用于跨沪深港 ETF 产品), 6 – 非沪深市场成份证券必须现金替代 (不适用于跨沪深港 ETF 产品)//7 – 港市退补现金替代 (仅适用于跨沪深港 ETF 产品),//8 – 港市必须现金替代 (仅适用于跨沪深港 ETF 产品)'),
        'premium_ratio': ('int', '溢价比例'),
        'discount_ratio': ('int', '折价比例'),
        'creation_cash_substitute': ('int', '申购替代金额 仅深圳有效'),
        'redemption_cash_substitute': ('int', '赎回替代金额 仅深圳有效'),
        'substitution_cash_amount': ('int', '替代总金额 仅上海有效'),
        'underlying_security_id': ('string', '成份证券所属市场 ID仅对跨市场债券(银行间)ETF启用'),
    },
    'fund_share': {
        '__source__': '手册「fund_share的字段说明」；列名与列序取自 wheel 的 columns_list（8 列）',
        'FUND_SHARE': ('float', '基金份额(万份)'),
        'CHANGE_REASON': ('string', '份额变动原因'),
        'IS_CONSOLIDATED_DATA': ('int', '是否合并数据 0：非合并数据1：合并数据2：合并数据，但该基金代码属于不实际交易基金'),
        'MARKET_CODE': ('string', '市场代码'),
        'ANN_DATE': ('string', '公告日期'),
        'TOTAL_SHARE': ('float', '基金总份额(万份)'),
        'CHANGE_DATE': ('string', '变动日期'),
        'FLOAT_SHARE': ('float', '流通份额(万份)'),
    },
    'fund_nav': {
        '__source__': '手册「fund_nav的字段说明」；列名与列序取自 wheel 的 columns_list（16 列）',
        'MARKET_CODE': ('string', '市场代码'),
        'ANN_DATE': ('string', '公告日期'),
        'PRICE_DATE': ('string', '截止日期：估算基金净值的交易日'),
        'UNIT_NAV': ('float', '单位净值'),
        'ACCUM_NAV': ('float', '累计净值'),
        'ACCUM_DIV': ('float', '累计分红'),
        'NAV_ADJ_FACTOR': ('float', '复权因子'),
        'IS_EX_DIVIDEND_DATE': ('int', '是否净值除权日'),
        'ACCUM_UNIT_DIST': ('float', '累计单位分配'),
        'TOTAL_NET_ASSET_VALUE': ('float', '合计资产净值'),
        'ADJ_UNIT_NAV': ('float', '复权单位净值'),
        'IS_MERGED_DATA': ('int', '是否合计数据'),
        'NET_ASSET_VALUE': ('float', '资产净值'),
        'INNER_CODE': ('string', '基金场内代码'),
        'OUTER_CODE': ('string', '基金场外代码'),
        'ACCUM_UNIT_NAV': ('float', '累计单位净值'),
    },
    'fund_iopv': {
        '__source__': '手册「fund_iopv的字段说明」；列名与列序取自 wheel 的 columns_list（3 列）',
        'MARKET_CODE': ('string', '市场代码'),
        'PRICE_DATE': ('string', '日期'),
        'IOPV_NAV': ('float', 'IOPV收盘净值'),
    },
    'index_constituent': {
        '__source__': '手册「index_constituent的字段说明」；列名与列序取自 wheel 的 columns_list（5 列）',
        'INDEX_CODE': ('string', '指数代码'),
        'CON_CODE': ('string', '成份股代码'),
        'INDATE': ('string', '纳入日期'),
        'OUTDATE': ('string', '剔除日期 未剔除时为 nan'),
        'INDEX_NAME': ('string', '指数名称'),
    },
    'index_weight': {
        '__source__': '手册「index_weight的字段说明」；列名与列序取自 wheel 的 columns_list（9 列）',
        'INDEX_CODE': ('string', '指数代码'),
        'CON_CODE': ('string', '标的代码'),
        'TRADE_DATE': ('string', '生效日期'),
        'TOTAL_SHARE': ('float', '总股本（股）'),
        'FREE_SHARE_RATIO': ('float', '自由流通比例（%） （归档后）'),
        'CALC_SHARE': ('float', '计算用股本（股）'),
        'WEIGHT_FACTOR': ('float', '权重因子'),
        'WEIGHT': ('float', '权重（%）'),
        'CLOSE': ('float', '收盘价'),
    },
    'industry_base_info': {
        '__source__': '手册「industry_base_info的字段说明」',
        'INDEX_CODE': ('string', '指数代码'),
        'INDUSTRY_CODE': ('string', '行业代码'),
        'LEVEL_TYPE': ('int', '指数类别'),
        'LEVEL1_NAME': ('string', '一级行业'),
        'LEVEL2_NAME': ('string', '二级行业'),
        'LEVEL3_NAME': ('string', '三级行业'),
        'IS_PUB': ('int', '是否发布 1：已发布；'),
        'CHANGE_REASON': ('string', '变动原因'),
    },
    'industry_constituent': {
        '__source__': '手册「industry_constituent的字段说明」；列名与列序取自 wheel 的 columns_list（5 列）',
        'INDEX_CODE': ('string', '指数代码'),
        'CON_CODE': ('string', '成份股代码'),
        'INDATE': ('string', '纳入日期'),
        'OUTDATE': ('string', '剔除日期 未剔除时为 nan'),
        'INDEX_NAME': ('string', '指数名称'),
    },
    'industry_weight': {
        '__source__': '手册「industry_weight的字段说明」；列名与列序取自 wheel 的 columns_list（4 列）',
        'WEIGHT': ('float', '权重'),
        'CON_CODE': ('string', '成份股代码'),
        'TRADE_DATE': ('string', '交易日期'),
        'INDEX_CODE': ('string', '指数代码'),
    },
    'industry_daily': {
        '__source__': '手册「industry_daily的字段说明」；列名与列序取自 wheel 的 columns_list（13 列）',
        'OPEN': ('float', '开盘价'),
        'HIGH': ('float', '最高价'),
        'CLOSE': ('float', '收盘价'),
        'LOW': ('float', '最低价'),
        'AMOUNT': ('float', '成交金额(元)'),
        'VOLUME': ('float', '成交量(股)'),
        'PB': ('float', '指数市净率'),
        'PE': ('float', '指数市盈率'),
        'TOTAL_CAP': ('float', '总市值(万元)'),
        'INDEX_CODE': ('string', '指数代码'),
        'A_FLOAT_CAP': ('float', 'A 股流通市值(万元)'),
        'PRE_CLOSE': ('float', '昨收盘价'),
        'TRADE_DATE': ('string', '交易日期'),
    },
    'kline_day': {
        '__source__': '手册附录 4.2.6「K线 Kline」+ 3.5.4.2 历史 K线',
        'code': ('str', '证券代码+市场（如 600000.SH）'),
        'kline_time': ('datetime', '交易所行情数据时间；日线为该交易日'),
        'open': ('float', '今开盘价'),
        'high': ('float', '最高价'),
        'low': ('float', '最低价'),
        'close': ('float', '收盘价'),
        'volume': ('int', '成交总量（股）'),
        'amount': ('float', '成交总金额（元）'),
    },
    'code_info': {
        '__source__': '手册 3.5.2.1；列名与列序取自 BaseData.get_code_info 的 pyc 常量',
        'code': ('str', '证券代码+市场（DataFrame 的 index，落盘时提为列）'),
        'symbol': ('str', '证券简称'),
        'security_status': ('str', '产品状态标志，见手册附录 4.1.6（1 停牌 / 2 除权 / 3 除息 / 4 风险警示 / 5 退市整理期 / 6 上市首日 …）'),
        'pre_close_price': ('float', '昨收价'),
        'high_limited': ('float', '涨停价'),
        'low_limited': ('float', '跌停价'),
        'price_tick': ('float', '最小价格变动单位'),
        'list_day': ('int', '上市日期。🔴 手册的输出说明里【没有列这一列】，实测 pyc 元组里有'),
    },
    'backward_factor': {
        '__source__': '手册 3.5.2.5；原始返回为宽表，落盘时 melt 成长表',
        'date': ('int', '交易日期（yyyymmdd）；原宽表的 index'),
        'code': ('str', '证券代码+市场；原宽表的 column'),
        'factor': ('float', '后复权因子。按交易所行情数据计算得出'),
    },
    'adj_factor': {
        '__source__': '手册 3.5.2.6；原始返回为宽表，落盘时 melt 成长表',
        'date': ('int', '交易日期（yyyymmdd）；原宽表的 index'),
        'code': ('str', '证券代码+市场；原宽表的 column'),
        'factor': ('float', '单次复权因子（除权除息当日的复权比例，非累乘）'),
    },
    'trading_calendar': {
        '__source__': '手册 3.5.2.8；get_calendar 返回 List[int]',
        'date': ('int', '交易日（yyyymmdd）'),
        'market': ('str', '市场（本脚本按 market 参数逐个市场取，落盘时标上）'),
    },
    'hist_code_list': {
        '__source__': '手册 3.5.2.7；get_hist_code_list 返回 List[str]',
        'code': ('str', '证券代码+市场。区间内**存在过**的代码（含已退市）'),
        'security_type': ('str', '取数时用的 security_type（本脚本落盘时标上）'),
        'start_date': ('int', '取数区间起（本脚本落盘时标上）'),
        'end_date': ('int', '取数区间止（本脚本落盘时标上）'),
    },
}


def columns_of(table):
    """表的字段名列表（列序 = wheel 里 columns_list 的列序）。"""
    return [k for k in FIELDS[table] if k != '__source__']


def describe(table, field):
    """(类型, 说明)；查不到返回 ('', '')——**不猜**。"""
    return FIELDS.get(table, {}).get(field, ('', ''))
